# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 19:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('recipe', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('benefits', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cuisine', models.IntegerField(choices=[(0, 'Traditional'), (1, 'Lost'), (2, 'Continental')])),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
